test:
  clients:
    default:
      database: rack-crud-demo
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      database: rack-crud-demo
      hosts:
        - <%= ENV['MONGOHQ_URL'] %>
  options:
    raise_not_found_error: false
